[build]
  command   = "npm run build"
  # Você pode customizar a pasta de saída estática, mas o plugin
  # cuidará de gerar SSR e funções automaticamente.
  publish   = ".netlify/output/public"

[[plugins]]
  package = "@netlify/plugin-nextjs"
